# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vardiCpp <- function(dat, w, eps = 1e-7, max_iter = 100L) {
    .Call(`_lbrcforests_vardiCpp`, dat, w, eps, max_iter)
}

